Add truncate method to proto.TestRunner
alpstable/gidari pull request #345
Opened 2022-10-25 09:33 UTC by ash-kamrip

Resolves <#293

Due to some reasons I couldn't test the code , kindly let me know if any changes are required.

2022-10-25 15:34 UTC, ash-kamrip commented
@prestonvasquez could you give it a try

2022-10-26 05:44 UTC, ash-kamrip commented
@prestonvasquez  is it looking good now ?!

2022-10-29 06:29 UTC, ash-kamrip commented
@prestonvasquez Hi Preston, could you let me know if any further changes are required ? I want to close this off before hacktoberfest ends?!

2022-10-29 18:32 UTC, prestonvasquez requested changes
@rangzen Need to fix the linting failures

2022-10-30 04:49 UTC, ash-kamrip commented on internal/proto/test_runner.go
> +func (runner TestRunner) AddTruncateCases(cases ...TestCase) {
Oopsies , wasn't able to run tests , i always got no tests while trying to run the tests , I missed this somehow. Thank you very much for helping out

2022-10-30 04:50 UTC, ash-kamrip commented on internal/proto/test_runner.go
> +// Adding cases for testing out the Truncate() storage method on multiple tables
@prestonvasquez Thanks for this as well, not versed with the github actions and checking logs, I've learned them now thanks to your gidari and the time you've taken out to review this 😄

2022-10-30 06:23 UTC, merged

2022-11-07 23:12 UTC, rangzen commented
@prestonvasquez Hello, sorry I wasn't available, do you still need something on this PR?